/*

 BACKGROUND1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : test.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Background1_h_INCLUDE
#define __Background1_h_INCLUDE

#define Background1Width 32
#define Background1Height 18
#define Background1Bank 0

extern const unsigned char Background1[];

#endif

/* End of BACKGROUND1.H */
