/*

 FLOORMAP_FULL_SEGMENTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 18
   Tile set      : test.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : Yes
   Block size    : 18

 This file was generated by GBMB v1.8

*/
#ifndef __floormap_full_segments_h_INCLUDE
#define __floormap_full_segments_h_INCLUDE

#define floormap_fullWidth 128
#define floormap_fullHeight 18
#define floormap_fullBank 0

extern const unsigned char floormap_fullBLK0[];
extern const unsigned char floormap_fullBLK1[];
extern const unsigned char floormap_fullBLK2[];
extern const unsigned char floormap_fullBLK3[];
extern const unsigned char floormap_fullBLK4[];
extern const unsigned char floormap_fullBLK5[];
extern const unsigned char floormap_fullBLK6[];
extern const unsigned char floormap_fullBLK7[];
extern const unsigned char floormap_fullBLK8[];
extern const unsigned char floormap_fullBLK9[];
extern const unsigned char floormap_fullBLK10[];
extern const unsigned char floormap_fullBLK11[];
extern const unsigned char floormap_fullBLK12[];
extern const unsigned char floormap_fullBLK13[];
extern const unsigned char floormap_fullBLK14[];
extern const unsigned char floormap_fullBLK15[];
extern const unsigned char floormap_fullBLK16[];
extern const unsigned char floormap_fullBLK17[];
extern const unsigned char floormap_fullBLK18[];
extern const unsigned char floormap_fullBLK19[];
extern const unsigned char floormap_fullBLK20[];
extern const unsigned char floormap_fullBLK21[];
extern const unsigned char floormap_fullBLK22[];
extern const unsigned char floormap_fullBLK23[];
extern const unsigned char floormap_fullBLK24[];
extern const unsigned char floormap_fullBLK25[];
extern const unsigned char floormap_fullBLK26[];
extern const unsigned char floormap_fullBLK27[];
extern const unsigned char floormap_fullBLK28[];
extern const unsigned char floormap_fullBLK29[];
extern const unsigned char floormap_fullBLK30[];
extern const unsigned char floormap_fullBLK31[];
extern const unsigned char floormap_fullBLK32[];
extern const unsigned char floormap_fullBLK33[];
extern const unsigned char floormap_fullBLK34[];
extern const unsigned char floormap_fullBLK35[];
extern const unsigned char floormap_fullBLK36[];
extern const unsigned char floormap_fullBLK37[];
extern const unsigned char floormap_fullBLK38[];
extern const unsigned char floormap_fullBLK39[];
extern const unsigned char floormap_fullBLK40[];
extern const unsigned char floormap_fullBLK41[];
extern const unsigned char floormap_fullBLK42[];
extern const unsigned char floormap_fullBLK43[];
extern const unsigned char floormap_fullBLK44[];
extern const unsigned char floormap_fullBLK45[];
extern const unsigned char floormap_fullBLK46[];
extern const unsigned char floormap_fullBLK47[];
extern const unsigned char floormap_fullBLK48[];
extern const unsigned char floormap_fullBLK49[];
extern const unsigned char floormap_fullBLK50[];
extern const unsigned char floormap_fullBLK51[];
extern const unsigned char floormap_fullBLK52[];
extern const unsigned char floormap_fullBLK53[];
extern const unsigned char floormap_fullBLK54[];
extern const unsigned char floormap_fullBLK55[];
extern const unsigned char floormap_fullBLK56[];
extern const unsigned char floormap_fullBLK57[];
extern const unsigned char floormap_fullBLK58[];
extern const unsigned char floormap_fullBLK59[];
extern const unsigned char floormap_fullBLK60[];
extern const unsigned char floormap_fullBLK61[];
extern const unsigned char floormap_fullBLK62[];
extern const unsigned char floormap_fullBLK63[];
extern const unsigned char floormap_fullBLK64[];
extern const unsigned char floormap_fullBLK65[];
extern const unsigned char floormap_fullBLK66[];
extern const unsigned char floormap_fullBLK67[];
extern const unsigned char floormap_fullBLK68[];
extern const unsigned char floormap_fullBLK69[];
extern const unsigned char floormap_fullBLK70[];
extern const unsigned char floormap_fullBLK71[];
extern const unsigned char floormap_fullBLK72[];
extern const unsigned char floormap_fullBLK73[];
extern const unsigned char floormap_fullBLK74[];
extern const unsigned char floormap_fullBLK75[];
extern const unsigned char floormap_fullBLK76[];
extern const unsigned char floormap_fullBLK77[];
extern const unsigned char floormap_fullBLK78[];
extern const unsigned char floormap_fullBLK79[];
extern const unsigned char floormap_fullBLK80[];
extern const unsigned char floormap_fullBLK81[];
extern const unsigned char floormap_fullBLK82[];
extern const unsigned char floormap_fullBLK83[];
extern const unsigned char floormap_fullBLK84[];
extern const unsigned char floormap_fullBLK85[];
extern const unsigned char floormap_fullBLK86[];
extern const unsigned char floormap_fullBLK87[];
extern const unsigned char floormap_fullBLK88[];
extern const unsigned char floormap_fullBLK89[];
extern const unsigned char floormap_fullBLK90[];
extern const unsigned char floormap_fullBLK91[];
extern const unsigned char floormap_fullBLK92[];
extern const unsigned char floormap_fullBLK93[];
extern const unsigned char floormap_fullBLK94[];
extern const unsigned char floormap_fullBLK95[];
extern const unsigned char floormap_fullBLK96[];
extern const unsigned char floormap_fullBLK97[];
extern const unsigned char floormap_fullBLK98[];
extern const unsigned char floormap_fullBLK99[];
extern const unsigned char floormap_fullBLK100[];
extern const unsigned char floormap_fullBLK101[];
extern const unsigned char floormap_fullBLK102[];
extern const unsigned char floormap_fullBLK103[];
extern const unsigned char floormap_fullBLK104[];
extern const unsigned char floormap_fullBLK105[];
extern const unsigned char floormap_fullBLK106[];
extern const unsigned char floormap_fullBLK107[];
extern const unsigned char floormap_fullBLK108[];
extern const unsigned char floormap_fullBLK109[];
extern const unsigned char floormap_fullBLK110[];
extern const unsigned char floormap_fullBLK111[];
extern const unsigned char floormap_fullBLK112[];
extern const unsigned char floormap_fullBLK113[];
extern const unsigned char floormap_fullBLK114[];
extern const unsigned char floormap_fullBLK115[];
extern const unsigned char floormap_fullBLK116[];
extern const unsigned char floormap_fullBLK117[];
extern const unsigned char floormap_fullBLK118[];
extern const unsigned char floormap_fullBLK119[];
extern const unsigned char floormap_fullBLK120[];
extern const unsigned char floormap_fullBLK121[];
extern const unsigned char floormap_fullBLK122[];
extern const unsigned char floormap_fullBLK123[];
extern const unsigned char floormap_fullBLK124[];
extern const unsigned char floormap_fullBLK125[];
extern const unsigned char floormap_fullBLK126[];
extern const unsigned char floormap_fullBLK127[];

#endif

/* End of FLOORMAP_FULL_SEGMENTS.H */
