/*

 BG1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 160 x 18
   Tile set      : Z:\home\rafagars\Documentos\gbdk\GBTD\test.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BG1_h_INCLUDE
#define __BG1_h_INCLUDE

#define BG1Width 160
#define BG1Height 18
#define BG1Bank 0

extern const unsigned char BG1[];

#endif

/* End of BG1.H */
