/*

 FLOORMAP_FULL_SEGMENTS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 18
   Tile set      : Z:\home\rafagars\Documentos\gbdk\GBTD\Pacby_Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : Yes
   Block size    : 18

 This file was generated by GBMB v1.8

*/
#ifndef __floormap_full_segments_h_INCLUDE
#define __floormap_full_segments_h_INCLUDE

#define floormap_fullWidth 128
#define floormap_fullHeight 18
#define floormap_fullBank 0

extern const unsigned char floormap_full[128][18];

#endif

/* End of FLOORMAP_FULL_SEGMENTS.H */
