/*

 PACBY_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Pacby_sprites_h_INCLUDE
#define __Pacby_sprites_h_INCLUDE

/* Bank of tiles. */
#define Pacby_spriteBank 0
/* CGBpalette entries. */
extern const unsigned char Pacby_spriteCGB[];
/* Start of tile array. */
extern const unsigned char Pacby_sprite[];

#endif

/* End of PACBY_SPRITES.H */
