/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 20

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_h_INCLUDE
#define __Tiles_h_INCLUDE

/* Bank of tiles. */
#define TilesBank 0

/* Super Gameboy palette 0 */
#define TilesSGBPal0c0 6076
#define TilesSGBPal0c1 8935
#define TilesSGBPal0c2 6596
#define TilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TilesSGBPal1c0 6076
#define TilesSGBPal1c1 8935
#define TilesSGBPal1c2 6596
#define TilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TilesSGBPal2c0 6076
#define TilesSGBPal2c1 8935
#define TilesSGBPal2c2 6596
#define TilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TilesSGBPal3c0 6076
#define TilesSGBPal3c1 8935
#define TilesSGBPal3c2 6596
#define TilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TilesCGBPal0c0 31707
#define TilesCGBPal0c1 9855
#define TilesCGBPal0c2 8935
#define TilesCGBPal0c3 64

/* Gameboy Color palette 1 */
#define TilesCGBPal1c0 31707
#define TilesCGBPal1c1 31702
#define TilesCGBPal1c2 31438
#define TilesCGBPal1c3 1024

/* Gameboy Color palette 2 */
#define TilesCGBPal2c0 32767
#define TilesCGBPal2c1 15326
#define TilesCGBPal2c2 6969
#define TilesCGBPal2c3 66

/* Gameboy Color palette 3 */
#define TilesCGBPal3c0 32767
#define TilesCGBPal3c1 95
#define TilesCGBPal3c2 113
#define TilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define TilesCGBPal4c0 6076
#define TilesCGBPal4c1 8935
#define TilesCGBPal4c2 6596
#define TilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TilesCGBPal5c0 6076
#define TilesCGBPal5c1 8935
#define TilesCGBPal5c2 6596
#define TilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TilesCGBPal6c0 6076
#define TilesCGBPal6c1 8935
#define TilesCGBPal6c2 6596
#define TilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TilesCGBPal7c0 6076
#define TilesCGBPal7c1 8935
#define TilesCGBPal7c2 6596
#define TilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char TilesCGB[];
/* Start of tile array. */
extern const unsigned char Tiles[];

#endif

/* End of TILES.H */
