/*

 TIMMY_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Timmy_sprite_h_INCLUDE
#define __Timmy_sprite_h_INCLUDE

/* Bank of tiles. */
#define TimmyBank 0
/* Start of tile array. */
extern const unsigned char Timmy[];

#endif

/* End of TIMMY_SPRITE.H */
